### ISSUE TITLE
Device Code Flow does not immediately invoke the provided Consumer for device code message

### ISSUE THREAD

**Issue by KRISHNAKUMARC27** [Azure-Samples/ms-identity-java-devicecodeflow#10]
**Description:**
When using the MSAL4J library to implement the device code flow for Azure OAuth2.0 authentication, the provided Consumer<DeviceCode> is not immediately invoked upon calling acquireToken, making it difficult to retrieve the device code message.

**Expected Behavior:**
The Consumer<DeviceCode> should be invoked immediately upon starting the device code flow, allowing immediate access to the deviceCode.message().

**Actual Behavior:**
The Consumer<DeviceCode> is not invoked immediately, leading to challenges in promptly providing the device code message to end users.

**Steps to Reproduce:**

1. Set up a PublicClientApplication instance.
2. Call acquireToken with DeviceCodeFlowParameters.builder, providing a Consumer<DeviceCode> to capture the device code message.
3. Observe that the consumer is not immediately invoked.

`PublicClientApplication pca = PublicClientApplication.builder(CLIENT_ID).authority(AUTHORITY).build();
AtomicReference<String> messageRef = new AtomicReference<>();

Consumer<DeviceCode> deviceCodeConsumer = (DeviceCode deviceCode) -> {
    messageRef.set(deviceCode.message());
};

CompletableFuture<IAuthenticationResult> future = pca.acquireToken(
    DeviceCodeFlowParameters.builder(SCOPE, deviceCodeConsumer).build()
);

// Expected: messageRef should now contain the device code message.
// Actual: messageRef is still null.
`

**Environment:**

MSAL4J version: 1.13.10
Java version: Zulu 11
Operating System: Windows 10

**Comment by Avery-Dunn** [comment]
Hello @KRISHNAKUMARC27 : Just to clarify, what sort information are you looking for in an immediate invocation?

Ignoring some of the helper classes/methods, the device code flow goes likes this:
- Call [PublicClientApplication.acquireToken](https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/39eb7d8f8a4394165b919187af984daac67cbcf7/msal4j-sdk/src/main/java/com/microsoft/aad/msal4j/PublicClientApplication.java#L67) with the DeviceCodeFlowParameters 
- [AbstractClientApplicationBase.executeRequest](https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/39eb7d8f8a4394165b919187af984daac67cbcf7/msal4j-sdk/src/main/java/com/microsoft/aad/msal4j/AbstractClientApplicationBase.java#L228) is called internally, a future is returned immediately that promises to have the result of `executeRequest`
- `executeRequest` determines the appropriate `*Supplier` class to provide the `AuthenticationResult`, and [AcquireTokenByDeviceCodeFlowSupplier.execute](https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/msal4j-sdk/src/main/java/com/microsoft/aad/msal4j/AcquireTokenByDeviceCodeFlowSupplier.java#L20) begins asynchronously executing
- The first step of the execution is to make the HTTP request to get the device code and [call the consumer's accept method ](https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/39eb7d8f8a4394165b919187af984daac67cbcf7/msal4j-sdk/src/main/java/com/microsoft/aad/msal4j/AcquireTokenByDeviceCodeFlowSupplier.java#L30) with the `DeviceCode` object created from the request.

That final step is the first time we'd have a DeviceCode object to send to the consumer, and there's not a lot of useful information we could send before that. Using your example, messageRef gets set about ~250 milliseconds after `acquireToken` is called, and most of that is just the required HTTP call.

**Comment by KRISHNAKUMARC27** [comment]
Thanks for the reply Avery. I tried the python version and dotNet version where we are able to return the message with the URL and code to the user immediately. For the Java version as you said, I added CompletableFuture which waits for the message to be set. It works.
Have added a timeout of 10 seconds. 

`	@GetMapping("/deviceCode/{username}")
	public ResponseEntity<String> getDeviceCode(@PathVariable String username) throws Exception {
		AtomicReference<String> messageRef = new AtomicReference<>();
		CompletableFuture<Void> messageSetFuture = new CompletableFuture<>();

		Consumer<DeviceCode> deviceCodeConsumer = (DeviceCode deviceCode) -> {
			messageRef.set(deviceCode.message());
			messageSetFuture.complete(null); // Complete the future when the message is set
		};

		PublicClientApplication pca = PublicClientApplication.builder(CLIENT_ID).authority(AUTHORITY)
				.setTokenCacheAccessAspect(tokenCacheAspect).build();

		CompletableFuture<IAuthenticationResult> future = pca
				.acquireToken(DeviceCodeFlowParameters.builder(SCOPE, deviceCodeConsumer).build());

		// Wait for the message to be set or timeout after 10 seconds
		try {
			messageSetFuture.orTimeout(10, TimeUnit.SECONDS).join();
		} catch (Exception e) {
			return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body("Failed to start device code flow.");
		}

		String message = messageRef.get();
		if (message == null) {
			return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body("Failed to start device code flow.");
		}

		return ResponseEntity.ok(message);
	}`
	
Any suggestions or improvements here or alternate ways to achieve the same? Also about 10 seconds timeout your recommendations would be helpful.

Thanks a lot.

**Comment by Avery-Dunn** [comment]
Could you describe what you mean by 'immediate'? How quickly is Python and .NET returning you the codes/URL? After a few tests I'm consistently getting the device code in about 200-250ms (about 90% of that delay is the HTTP call), so a 10 second timeout seems very excessive.
