### ISSUE TITLE
AppCreation script fails because of bad file path

### ISSUE THREAD

**Issue by bgavrilMS** [Azure-Samples/ms-identity-java-devicecodeflow#3]
1. Run `Configure.ps1` script
2. Enter credentials etc. 

Actual: the provisioning works, but the script cannot update the sample file because of a bad path. 

The correct path is: C:\g\sample\others\ms-identity-java-devicecodeflow\src\main\java\DeviceCodeFlow

Get-Content : Cannot find path 'C:\g\sample\others\ms-identity-java-devicecodeflow\java\DeviceCodeFlow' because it
does not exist.
At C:\g\sample\others\ms-identity-java-devicecodeflow\AppCreationScripts\Configure.ps1:93 char:14

**Comment by jmprieur** [comment]
Note the file to change is the sample.json (not the script directly)

**Comment by bgavrilMS** [comment]
Ok cool, I’ll try to fix it then.

**Comment by TiagoBrenck** [comment]
A friendly reminder that the powershell wont change the code settings automatically because currently we don't have a function that reads and replace values in `.java` extensions.

**Comment by jmprieur** [comment]
What do you mean, @TiagoBrenck ?
We can use text substitution? I've written Java / Python sample.json that do work in the initial samples?

**Comment by TiagoBrenck** [comment]
I remember when Ramya was struggling with an error on `Configure.ps1` because the function `UpdateTextFile` couldn't read the file. If you have it working in other samples, then ignore my comment.

**Comment by jmprieur** [comment]
This is probably because that was the wrong file :(
We need to re-add the code in the samples.json where this was removed:

cc: @navyasric @sangonzal

**Comment by navyasric** [comment]
CC: @abhidnya13 Had this same issue in app creation script for https://github.com/Azure-Samples/ms-identity-python-webapp
