### ISSUE TITLE
Sample does not showcase AcquireTokenSilent best practice

### ISSUE THREAD

**Issue by bgavrilMS** [Azure-Samples/ms-identity-java-devicecodeflow#4]
MSAL libraries must call `AcquireTokenSilent`. Even for U/P flow, this provides the benefit that it can find a fresh AT in the cache, so it eliminates the need to make a network call. This also lowers COGS for AAD.

**Comment by sangonzal** [comment]
https://github.com/Azure-Samples/ms-identity-java-devicecodeflow/pull/6
